server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebrainsoft_study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ebsoft
    password: ebsoft
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

file:
  dir: C:\Users\ellie\SpringBoot_Project\src\main\resources\upload\
  lecture_dir: C:\Users\ellie\SpringBoot_Project\src\main\resources\upload\
  course_dir: C:\Users\ellie\SpringBoot_Project\src\main\resources\upload\